Changes to be committed: 	modified:   OFPC/CXDB.pm 	modified:   OFPC/Common.pm 	modified:   OFPC/Parse.pm 	modified:   openfpc 	modified:   openfpc-client 	modified:   openfpc-cx2db 	modified:   openfpc-dbmaint
- Status to a proxy now works
- Status to a proxy shows proxy data as well as node
- dbmaint now adds a proxy DB
- Much better logging output (syslog) for cx2db
- cx2db now exits with the right error when it cant connect to the DB
- dbmaint output cleaned up
- openfpc output cleaned up
- dbmaint only restarts the node that is edited
-

diff --git a/openfpc-dbmaint b/openfpc-dbmaint
--- a/openfpc-dbmaint
+++ b/openfpc-dbmaint
@@ -28,6 +28,22 @@ ACTION=$1
 TYPE=$2
 CONFIG=$3
 
+# Default values for configuration in case user chooses to not include
+# unneeded values in the config file. E.g. GUI_DB_NAME when the GUI
+# is not being used.
+# Change them in your openfpc config file, not here. They are replaced at runtime
+
+ENABLE_SESSION=0
+SESSION_DB_NAME="openfpc" 
+SESSION_DB_USER="openfpc"
+SESSION_DB_PASS="openfpc"
+GUI_DB_NAME="gui"
+GUI_DB_USER="opnepfc"
+GUI_DB_PASS="openfpc"
+PROXY_DB_NAME="proxy_openfpc"
+PROXY_DB_USER="openfpc"
+PROXY_DB_PASSWORD="openfpc"
+
 function die
 {
 	echo ERROR: $1
@@ -47,7 +63,7 @@ function chkroot()
 function addfuncs
 {
 	# Create mysql IPv6 functions
-	echo Adding function INET_ATON6... to DB $SESSION_DB_NAME
+	echo -e " -  Adding function INET_ATON6 to DB $SESSION_DB_NAME"
 	SQL="
 use $SESSION_DB_NAME;
 DELIMITER //
@@ -116,16 +132,17 @@ function readconfig
 		[ -n "$SESSION_DB_USER" ] || die "SESSION_DB_USER not set in $CONFIG"
 		[ -n "$SESSION_DB_PASS" ] || die "SESSION_DB_PASS not set in $CONFIG"
 		[ -n "$NODENAME" ] || die "NODENAME not set in $CONFIG"
-                [ -n "$GUI_DB_NAME" ] || die "GUI_DB_NAME not set in $CONFIG"
-                [ -n "$GUI_DB_USER" ] || die "GUI_DB_USER not set in $CONFIG"
-                [ -n "$GUI_DB_PASS" ] || die "GUI_DB_PASS not set in $CONFIG"
-                [ -n "$PASSWD" ] || die "PASSWD file not set in $CONFIG"
+    [ -n "$GUI_DB_NAME" ] || die "GUI_DB_NAME not set in $CONFIG"
+    [ -n "$GUI_DB_USER" ] || die "GUI_DB_USER not set in $CONFIG"
+    [ -n "$GUI_DB_PASS" ] || die "GUI_DB_PASS not set in $CONFIG"
+    [ -n "$PASSWD" ] || die "PASSWD file not set in $CONFIG"
                 
 		echo -e "[*] Enter mysql \"root\" credentials to connect to your local mysql server in order to create the databases"
 		read -p "    DB root Username: " DBUSER
 		stty -echo
 		read -p "    DB root Password: " DBPASS
 		stty echo
+    echo -e "\n"
                 
                 # Check we can access DB with these creds
                 mysql -u$DBUSER -p$DBPASS -e 'SHOW DATABASES;' > /dev/null || die "Unable to connect to database - Did you enter the correct user/password?"
@@ -195,6 +212,77 @@ function configure_gui
     fi
 }
 
+
+function create_proxy
+{
+  
+  echo -e "[*] Creating proxy database\n" 
+  # Test we have access
+
+  # Check if DB already exist
+  mysql -u$DBUSER -p$DBPASS -e "USE $PROXY_DB_NAME;" > /dev/null 2>&1 && die "Database $PROXY_DB_NAME already exists"
+
+  # Create new DB
+  mysql -u$DBUSER -p$DBPASS -e "CREATE DATABASE $PROXY_DB_NAME;" > /dev/null 2>&1 || die "Unable to create DB $PROXY_DB_NAME - Did you enter the correct user/password?"
+
+    # Create new DB user
+  mysql -u$DBUSER -p$DBPASS -e "use 'mysql'; CREATE USER '$PROXY_DB_USER'@'localhost' IDENTIFIED BY '$PROXY_DB_PASS';"
+  mysql -u$DBUSER -p$DBPASS -e "use $PROXY_DB_NAME; GRANT ALL PRIVILEGES ON $PROXY_DB_NAME.* TO '$PROXY_DB_USER'@'localhost';"
+
+
+  echo -e "    OpenFPC Proxy DB Created.\n";
+    
+  # Create tables
+  SQL="CREATE TABLE search (
+         id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
+         search_id       INT UNSIGNED NOT NULL, 
+         timestamp DATETIME,
+         username VARCHAR(20),
+         description VARCHAR(100),
+         search VARCHAR(500) 
+         );"
+  mysql -u$DBUSER -p$DBPASS $PROXY_DB_NAME -e "$SQL"
+  SQL="CREATE TABLE IF NOT EXISTS session              \
+        (                                                  \
+        id            INT                        NOT NULL, \
+        search_id     INT UNSIGNED        NOT NULL, \
+        start_time    DATETIME                   NOT NULL, \
+        ip_proto      TINYINT UNSIGNED           NOT NULL, \
+        ip_version    TINYINT UNSIGNED           NOT NULL, \
+        src_ip        DECIMAL(39,0) UNSIGNED,              \
+        src_port      SMALLINT UNSIGNED,                   \
+        dst_ip        DECIMAL(39,0) UNSIGNED,              \
+        dst_port      SMALLINT UNSIGNED,                   \
+        src_pkts      INT UNSIGNED               NOT NULL, \
+        src_bytes     INT UNSIGNED               NOT NULL, \
+        dst_pkts      INT UNSIGNED               NOT NULL, \
+        dst_bytes     INT UNSIGNED               NOT NULL, \
+        node          CHAR(100),
+        PRIMARY KEY (id,search_id),                       \
+        INDEX src_ip (src_ip),                             \
+        INDEX dst_ip (dst_ip),                             \
+        INDEX dst_port (dst_port),                         \
+        INDEX src_port (src_port),                         \
+        INDEX start_time (start_time)                      \
+        ) ENGINE=MyISAM                                    \
+        ";
+  mysql -u$DBUSER -p$DBPASS $PROXY_DB_NAME -e "$SQL"
+    
+}
+
+function drop_proxy
+{
+  echo -e "[*] Removing proxy database $NODENAME"
+  # Test we have access
+  mysql -u$DBUSER -p$DBPASS -e 'SHOW DATABASES;' > /dev/null 2>&1 || die "Unable to connect to database"
+  # Check if DB already exists
+  mysql -u$DBUSER -p$DBPASS -e "USE $PROXY_DB_NAME;" > /dev/null 2>&1 || die "Database $PROXY_DB_NAME Not found!"
+  mysql -u$DBUSER -p$DBPASS -e "DROP DATABASE $PROXY_DB_NAME;" > /dev/null 2>&1 || die "Database $PROXY_DB_NAME Not found!"
+  mysql -u$DBUSER -p$DBPASS -e "use 'mysql'; DROP USER '$PROXY_DB_USER'@'localhost';" || die "Unable to remove user $PROXY_DB_USER"
+
+  echo -e " -  Proxy database removed."
+}
+
 function create_gui
 {
 
@@ -257,8 +345,7 @@ function drop_gui
 
 function create_session
 {
-	echo CREATING DATABASE
-	echo ---------------------------
+  echo "[*] Creating Session database on $NODENAME"
 	# Test we have access
 	mysql -u$DBUSER -p$DBPASS -e 'SHOW DATABASES;' > /dev/null || die "Unable to connect to database"
 
@@ -271,13 +358,12 @@ function create_session
 	# Create new DB user
 	mysql -u$DBUSER -p$DBPASS -e "use 'mysql'; CREATE USER '$SESSION_DB_USER'@'localhost' IDENTIFIED BY '$SESSION_DB_PASS';"
 	mysql -u$DBUSER -p$DBPASS -e "use $SESSION_DB_NAME; GRANT ALL PRIVILEGES ON $SESSION_DB_NAME.* TO '$SESSION_DB_USER'@'localhost';"
-	echo Session DB Created.
+	echo -e " -  Session DB Created"
 }
 
 function drop_session
 {
-	echo REMOVING DATABASE
-	echo ---------------------------
+	echo -e "[*] Removing session database $NODENAME";
 	# Test we have access
 	mysql -u$DBUSER -p$DBPASS -e 'SHOW DATABASES;' > /dev/null 2>&1 || die "Unable to connect to database"
 	# Check if DB already exists
@@ -285,7 +371,7 @@ function drop_session
 	mysql -u$DBUSER -p$DBPASS -e "DROP DATABASE $SESSION_DB_NAME;" > /dev/null 2>&1 || die "Database $SESSION_DB_NAME Not found!"
 	mysql -u$DBUSER -p$DBPASS -e "use 'mysql'; DROP USER '$SESSION_DB_USER'@'localhost';" || die "Unable to remove user $SESSION_DB_USER"
 
-	echo Session DB Dropped.
+  echo -e " -  Session database removed";
 }
 
 function showhelp
@@ -297,7 +383,7 @@ function showhelp
     echo -e "  Usage:"
     echo -e "  openfpc-dbmaint.sh <action> <db_type> <config_file>\n"
     echo -e "      action          create / drop"
-    echo -e "      db_type         session / gui"
+    echo -e "      db_type         session / gui / proxy"
     echo -e "      config_file     /path/to/openfpc-config.conf"
     echo -e ""
     echo -e "  Example 1: Creating a session database"
@@ -311,9 +397,9 @@ function showhelp
 
 function restartopenfpc
 {
-    echo -e "[*] Restarting OpenFPC\n"
-    openfpc -a stop
-    openfpc -a start
+    echo -e "[*] Restarting OpenFPC Node $NODENAME"
+    openfpc -a stop -t $NODENAME
+    openfpc -a start -t $NODENAME
 }
 
 ARGC=$#
@@ -325,39 +411,44 @@ fi
 
 case $1 in 
 	create)
-       	    chkroot	
-            readconfig
-            
-            if [ "$TYPE" == "session" ]
-            then
-		configure_session
-                create_session
-		addfuncs
-                restartopenfpc
-            elif [ "$TYPE" == "gui" ]
-            then
-                configure_gui
-                create_gui
-                restartopenfpc
-                echo -e "[*] DB Configured and admin user added. Now navigate to http://<ip.add.re.ss>/openfpc/\n"
-            else
-                die "ERROR: Invalid type $TYPE. See usage"
-            fi
+    chkroot	
+    readconfig
+          
+    if [ "$TYPE" == "session" ]
+    then
+		  configure_session
+      create_session
+		  addfuncs
+      restartopenfpc
+    elif [ "$TYPE" == "gui" ]
+    then
+      configure_gui
+      create_gui
+      restartopenfpc
+      echo -e "[*] DB Configured and admin user added. Now navigate to http://<ip.add.re.ss>/openfpc/\n"
+    elif [ "$TYPE" == "proxy" ]
+    then
+      create_proxy
+    else
+      die "Invalid database type $TYPE. See usage"
+    fi
 	;;
 
 	drop)
-            chkroot
-            readconfig
-            
-            if [ "$TYPE" == "session" ]
-            then
-		drop_session
-            elif [ "$TYPE" == "gui" ]
-            then
-                drop_gui
-            else
-                die "ERROR: Invalid type $TYPE. See usage"
-            fi
+    chkroot
+    readconfig
+    if [ "$TYPE" == "session" ]
+    then
+		  drop_session
+    elif [ "$TYPE" == "gui" ]
+    then
+      drop_gui
+    elif [ "$TYPE" == "proxy" ]
+    then
+      drop_proxy
+    else
+      die "ERROR: Invalid type $TYPE. See usage"
+    fi
 	;;
 	clean)
 	;;
