Test for - in a dbname before creating db

diff --git a/openfpc-dbmaint b/openfpc-dbmaint
--- a/openfpc-dbmaint
+++ b/openfpc-dbmaint
@@ -127,16 +127,19 @@ function readconfig
     if [ -f $CONFIG ] ; then
 		source $CONFIG || die "Unable to read config file \"$CONFIG\""
 		# Check all vars required are set in $CONFIG
-		[ -n "$ENABLE_SESSION" ] || die "ENABLE_SESSION not set in $CONFIG"
-		[ -n "$SESSION_DB_NAME" ] || die "SESSION_DB_NAME not set in $CONFIG"
-		[ -n "$SESSION_DB_USER" ] || die "SESSION_DB_USER not set in $CONFIG"
-		[ -n "$SESSION_DB_PASS" ] || die "SESSION_DB_PASS not set in $CONFIG"
+		[ -n "$ENABLE_SESSION" ] || die "ENABLE_SESSION not defined in $CONFIG"
 		[ -n "$NODENAME" ] || die "NODENAME not set in $CONFIG"
-    [ -n "$GUI_DB_NAME" ] || die "GUI_DB_NAME not set in $CONFIG"
-    [ -n "$GUI_DB_USER" ] || die "GUI_DB_USER not set in $CONFIG"
-    [ -n "$GUI_DB_PASS" ] || die "GUI_DB_PASS not set in $CONFIG"
     [ -n "$PASSWD" ] || die "PASSWD file not set in $CONFIG"
-                
+
+    # check db names for invalid chars
+    DBNAMES="$SESSION_DB_NAME $GUI_DB_NAME $PROXY_DB_NAME"
+
+    for i in $DBNAMES 
+    do
+      echo $i | grep - > /dev/null && die "Error in Database name $i. Name cannot contain a '-' character."
+    done
+
+
 		echo -e "[*] Enter mysql \"root\" credentials to connect to your local mysql server in order to create the databases"
 		read -p "    DB root Username: " DBUSER
 		stty -echo
@@ -398,8 +401,8 @@ function showhelp
 function restartopenfpc
 {
     echo -e "[*] Restarting OpenFPC Node $NODENAME"
-    openfpc -a stop -t $NODENAME
-    openfpc -a start -t $NODENAME
+    sudo openfpc -a stop -t $NODENAME
+    sudo openfpc -a start -t $NODENAME
 }
 
 ARGC=$#
