Add or update initial user at install

diff --git a/trunk/openfpc-dbmaint b/trunk/openfpc-dbmaint
--- a/trunk/openfpc-dbmaint
+++ b/trunk/openfpc-dbmaint
@@ -1,13 +1,13 @@
 #!/bin/bash 
 
 #########################################################################################
-# Copyright (C) 2010 Leon Ward 
+# Copyright (C) 2010 Leon Ward
+# leon@openfpc.org
 # openfpc-dbmaint.pl - Part of the OpenFPC - (Full Packet Capture) project
 #
 # Quick script to create an OpenFPC connection database.
 #
-# The mysql function source in addfuncs() came from edward@openfpc.org
-# -Leon 
+# The mysql IPv6 function source in addfuncs() came from edward@openfpc.org
 #########################################################################################
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
@@ -107,6 +107,7 @@ DELIMITER ;
 
 function readconfig
 {
+    # Read in configuration from $CONFIG file.
     if [ -f $CONFIG ] ; then
 		source $CONFIG || die "Unable to read config file \"$CONFIG\""
 		# Check all vars required are set in $CONFIG
@@ -119,11 +120,14 @@ function readconfig
                 [ -n "$GUI_DB_USER" ] || die "GUI_DB_USER not set in $CONFIG"
                 [ -n "$GUI_DB_PASS" ] || die "GUI_DB_PASS not set in $CONFIG"
                 
-		echo -e "[*] Enter mysql \"root\" credentials to connect to your local mysql server in order to create $SESSION_DB_NAME database"
+		echo -e "[*] Enter mysql \"root\" credentials to connect to your local mysql server in order to create the databases"
 		read -p "    DB root Username: " DBUSER
 		stty -echo
 		read -p "    DB root Password: " DBPASS
 		stty echo
+                
+                # Check we can access DB with these creds
+                mysql -u$DBUSER -p$DBPASS -e 'SHOW DATABASES;' > /dev/null || die "Unable to connect to database - Did you enter the correct user/password?"
     else
         die "Cant find config file $CONFIG"
     fi
@@ -132,7 +136,6 @@ function readconfig
 
 function configure_session
 {
-
 		echo ---------------------------------------------------------
 		echo -e "[*] Working on Instance $CONFIG ."
 		read -p "    Would you like session capture ENABLED on $NODENAME? (y/n)"  SESSION_ON
@@ -153,7 +156,6 @@ function configure_session
 			echo -e "    You can find it here -> http://www.openfpc.org/downloads"
 			echo -e "    Continuing, but don't expect session capture to work until cxtracker is installed"
 		fi	
-
 }
 
 function configure_gui
@@ -170,7 +172,19 @@ function configure_gui
     DESCRIPTION="Administrator"
     TIMEZONE="Europe/London"
     DEFAULTNODE="None"
-     
+    
+    # Add this user to the openfpc $CONFIG to allow them to get pcaps
+    # 1 Check if the user already exists
+    
+    if grep ^USER=$ADMIN_USER= $CONFIG
+    then
+        echo FOUND USER $ADMIN_USER IN $CONFIG
+	sed -e "s/USER=$ADMIN_USER=.*/USER=$ADMIN_USER=$ADMIN_PASS/g" -i $CONFIG
+        
+    else
+        echo USER NOT FOUND. Adding $ADMIN_USER.
+        echo -e "USER=$ADMIN_USER=$ADMIN_PASS\n" >> $CONFIG
+    fi
 }
 
 function create_gui
@@ -179,13 +193,12 @@ function create_gui
     echo CREATING GUI DATABASE
     echo ---------------------------
     # Test we have access
-    mysql -u$DBUSER -p$DBPASS -e 'SHOW DATABASES;' > /dev/null || die "Unable to connect to database"
 
     # Check if DB already exists
     mysql -u$DBUSER -p$DBPASS -e "USE $GUI_DB_NAME;" > /dev/null 2>&1 && die "Database $GUI_DB_NAME already exists"
 
     # Create new DB
-    mysql -u$DBUSER -p$DBPASS -e "CREATE DATABASE $GUI_DB_NAME;" > /dev/null 2>&1 || die "Unable to create DB $GUI_DB_NAME"
+    mysql -u$DBUSER -p$DBPASS -e "CREATE DATABASE $GUI_DB_NAME;" > /dev/null 2>&1 || die "Unable to create DB $GUI_DB_NAME - Did you enter the correct user/password?"
 
     # Create new DB user
     mysql -u$DBUSER -p$DBPASS -e "use 'mysql'; CREATE USER '$GUI_DB_USER'@'localhost' IDENTIFIED BY '$GUI_DB_PASS';"
@@ -223,7 +236,7 @@ function drop_gui
     echo REMOVING DATABASE
     echo ---------------------------
     # Test we have access
-    mysql -u$DBUSER -p$DBPASS -e 'SHOW DATABASES;' > /dev/null 2>&1 || die "Unable to connect to database"
+    mysql -u$DBUSER -p$DBPASS -e 'SHOW DATABASES;' > /dev/null 2>&1 || die "Unable to connect to database - Did you enter the correct user/password"
     # Check if DB already exists
     mysql -u$DBUSER -p$DBPASS -e "USE $GUI_DB_NAME;" > /dev/null 2>&1 || die "Database $GUI_DB_NAME Not found!"
     
@@ -288,6 +301,13 @@ function showhelp
 
 }
 
+function restartopenfpc
+{
+    echo -e "[*] Restarting OpenFPC\n"
+    openfpc -a stop
+    openfpc -a start
+}
+
 ARGC=$#
 if [ "$ARGC" == "2" ] ; then 
 	echo -e "Error: incorrect arguements"
@@ -305,10 +325,13 @@ case $1 in
 		configure_session
                 create_session
 		addfuncs
+                restartopenfpc
             elif [ "$TYPE" == "gui" ]
             then
                 configure_gui
                 create_gui
+                restartopenfpc
+                echo -e "[*] DB Configured and admin user added. Now navigate to http://<ip.add.re.ss>/openfpc/\n"
             else
                 die "ERROR: Invalid type $TYPE. See usage"
             fi
