Added openfpc-common and fixed debian scripts

diff --git a/trunk/debian/openfpc-slave.postinst b/trunk/debian/openfpc-slave.postinst
--- a/trunk/debian/openfpc-slave.postinst
+++ b/trunk/debian/openfpc-slave.postinst
@@ -9,13 +9,11 @@ OFPC_DIR=/var/lib/openfpc
 SENSOR_DIR=$OFPC_DIR/$HOSTNAME/pcap
 
 if [ ! -d $SENSOR_DIR ]; then
-        if [ -w $OFPC_DIR ]; then
-                mkdir -vp $SENSOR_DIR || exit 74
-                chown -vR openfpc:openfpc $OFPC_DIR || exit 74
-        else
-                echo "Can't create folder in $OFPC_DIR. Please inspect."
+        mkdir -vp $SENSOR_DIR || exit 74
+        chown -vR openfpc:openfpc $OFPC_DIR || exit 74
+else
+        echo "Can't create folder in $OFPC_DIR. Please inspect."
 #                exit 77
-        fi
 fi
 
 update-rc.d  openfpc-slave defaults
